name: Build gendef

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:          # 支持手动触发

jobs:
  build-linux:
    name: 编译GenDef (Alpine)
    runs-on: alpine-latest
    steps:
      - name: Checkout mingw-w64
        uses: actions/checkout@v4
        with:
          repository: mingw-w64/mingw-w64
          path: mingw-w64
          ref: v14.0.0

      - name: 安装依赖
        run: |
          sudo apk update
          sudo apk add build-base

      - name: Configure & Build gendef
        working-directory: mingw-w64/mingw-w64-tools/gendef
        run: |
          ./configure --prefix=$GITHUB_WORKSPACE/install
          make -j$(nproc)
          make install-strip

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: gendef-linux-x86_64
          path: install/bin/gendef
          if-no-files-found: error
