name: 编译musl版本的gendef

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: 编译
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22 
    steps:
      - name: 安装编译工具
        run: apk add build-base
      - name: 克隆代码
        uses: actions/checkout@v4
        with:
          repository: mingw-w64/mingw-w64
          path: mingw-w64
          ref: v14.0.0

      - name: 编译代码
        working-directory: mingw-w64/mingw-w64-tools/gendef
        run: |   
          ./configure --prefix=/tmp/gendef-install CFLAGS="-static-libgcc -static-libstdc++ -static"
          make -j$(nproc)
          make install      

      - name: 制作发布包
        run: |
          mkdir -p release
          cp /tmp/gendef-install/bin/gendef release/gendef
      - name: 创建Release资源
        uses: softprops/action-gh-release@v2
        with:
          tag_name: gendef
          name: gendef
          body: |
            全静态 gendef
          files: |
            release/gendef
          draft: false
          prerelease: false
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
